apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: budge-tech
  name: appdeployemnt
spec:
  replicas: 6
  selector:
    matchLabels:
      app: budge-tech
  strategy: {}
  template:
    metadata:
      labels:
        app: budge-tech
    spec:
      containers:
      - image: ahmad75/chatbot:main-bc4f3c1
        name: budge-tech-app
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_HOST
        
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DB_USER
              
        - name: DB_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: PG_PASSWORD
        ports:
        - containerPort: 5000